#!/usr/bin/env python3
"""
CareFlow — Rajesh Sharma 시드 데이터 생성기 / Seed data generator.

용도 (Purpose):
    seed_rajesh.sql 의 health_metrics 시계열 INSERT 블록을 프로그래매틱하게
    재생성하고 싶을 때 사용하는 유틸리티. 기본 seed_rajesh.sql 은 PostgreSQL
    generate_series() 로 직접 시계열을 만들기 때문에 이 스크립트 없이도 동작한다.
    이 스크립트는 (a) AlloyDB 가 없는 환경에서 INSERT 문을 미리 뽑아보거나,
    (b) 노이즈/트렌드 공식을 튜닝하고 싶을 때 사용한다.

    This is a convenience generator. `seed_rajesh.sql` already seeds the 90-day
    time-series via `generate_series()`, so running this script is OPTIONAL.
    Use it when you want to (a) pre-render the INSERT statements offline, or
    (b) tweak the trend / noise formulas.

사용법 (Usage):
    python generate_seed.py > health_metrics_inline.sql

출력 (Output):
    Rajesh Sharma 환자(고정 UUID)의 90일치 혈압/혈당/체중/심박수 INSERT 문.
"""
from __future__ import annotations

import math
from datetime import datetime, timedelta

PATIENT_ID = "11111111-1111-1111-1111-111111111111"
START_DATE = datetime(2026, 1, 5)
DAYS = 90


def bp_systolic(day: int) -> float:
    # 135 -> 142 상승 추세 + 소폭 진동 / rising trend + small oscillation
    return round(135 + (day / (DAYS - 1)) * 7 + 2 * math.sin(day / 3))


def bp_diastolic(day: int) -> float:
    return round(85 + (day / (DAYS - 1)) * 5 + 1.5 * math.sin(day / 4))


def glucose(day: int) -> float:
    # 145 -> 128 개선 (Metformin 증량) / improvement after Metformin uptitration
    return round(145 - (day / (DAYS - 1)) * 17 + 3 * math.sin(day / 2.5))


def weight(day: int) -> float:
    return round(72 + 0.8 * math.sin(day / 5), 1)


def heart_rate(day: int) -> float:
    return round(74 + 4 * math.sin(day / 3.5))


def emit(metric: str, primary, secondary, unit: str, ts: datetime, source: str) -> str:
    sec = "NULL" if secondary is None else f"{secondary}"
    return (
        "INSERT INTO health_metrics "
        "(patient_id, metric_type, value_primary, value_secondary, unit, measured_at, source) "
        f"VALUES ('{PATIENT_ID}', '{metric}', {primary}, {sec}, '{unit}', "
        f"'{ts.strftime('%Y-%m-%d %H:%M:%S')}', '{source}');"
    )


def main() -> None:
    print("-- Auto-generated by generate_seed.py — DO NOT hand-edit.")
    print("-- 자동 생성 파일 — 직접 수정하지 말고 generate_seed.py 를 수정할 것.")
    print("BEGIN;")
    for day in range(DAYS):
        ts_bp = START_DATE + timedelta(days=day, hours=8)
        ts_gl = START_DATE + timedelta(days=day, hours=7, minutes=30)
        ts_wt = START_DATE + timedelta(days=day, hours=7)
        ts_hr = START_DATE + timedelta(days=day, hours=8, minutes=15)

        print(emit("blood_pressure", bp_systolic(day), bp_diastolic(day),
                   "mmHg", ts_bp, "self_report"))
        print(emit("blood_glucose", glucose(day), None,
                   "mg/dL", ts_gl, "self_report"))
        print(emit("weight", weight(day), None,
                   "kg", ts_wt, "self_report"))
        print(emit("heart_rate", heart_rate(day), None,
                   "bpm", ts_hr, "device"))
    print("COMMIT;")


if __name__ == "__main__":
    main()
